/**
 * Base class for all custom errors generated by WiseJSON DB.
 * Allows catching all library errors via `catch (e) { if (e instanceof WiseJSONError) ... }`.
 */
export class WiseJSONError extends Error {
  constructor(message: string) {
    super(message);
    // Explicitly set the prototype to ensure instanceof works correctly in TS/ES5
    Object.setPrototypeOf(this, new.target.prototype);
    this.name = this.constructor.name;

    if (Error.captureStackTrace) {
      Error.captureStackTrace(this, this.constructor);
    }
  }
}

/**
 * Error occurring when a unique index constraint is violated.
 */
export class UniqueConstraintError extends WiseJSONError {
  public readonly fieldName: string;
  public readonly value: any;

  /**
   * @param fieldName - Name of the field with the unique index.
   * @param value - The value that caused the conflict.
   */
  constructor(fieldName: string, value: any) {
    const valueStr = typeof value === 'string' ? `'${value}'` : String(value);
    super(`Duplicate value ${valueStr} for unique index on field '${fieldName}'.`);
    this.fieldName = fieldName;
    this.value = value;
  }
}

/**
 * Error occurring when a requested document is not found.
 */
export class DocumentNotFoundError extends WiseJSONError {
  public readonly docId: string;

  /**
   * @param docId - The ID of the document that was not found.
   */
  constructor(docId: string) {
    super(`Document with ID '${docId}' not found.`);
    this.docId = docId;
  }
}

/**
 * Error related to incorrect configuration, options, or invalid API usage.
 */
export class ConfigurationError extends WiseJSONError {
  constructor(message: string) {
    super(message);
  }
}
